// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/unittest_lazy_dependencies_enum.proto

#include "google/protobuf/unittest_lazy_dependencies_enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protobuf_unittest {
namespace lazy_imports {
}  // namespace lazy_imports
}  // namespace protobuf_unittest
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n5google/protobuf/unittest_lazy_dependen"
  "cies_enum.proto\022\036protobuf_unittest.lazy_"
  "imports*,\n\010LazyEnum\022\017\n\013LAZY_ENUM_0\020\000\022\017\n\013"
  "LAZY_ENUM_1\020\001B,B\034UnittestLazyImportsEnum"
  "ProtoH\001\200\001\001\210\001\001\220\001\001\370\001\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto = {
  false, false, descriptor_table_protodef_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto, "google/protobuf/unittest_lazy_dependencies_enum.proto", 179,
  &descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto_once, descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto_sccs, descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto::offsets,
  file_level_metadata_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto, 0, file_level_enum_descriptors_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto, file_level_service_descriptors_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto)), true);
namespace protobuf_unittest {
namespace lazy_imports {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LazyEnum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto);
  return file_level_enum_descriptors_google_2fprotobuf_2funittest_5flazy_5fdependencies_5fenum_2eproto[0];
}
bool LazyEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace lazy_imports
}  // namespace protobuf_unittest
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
