// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/unittest_preserve_unknown_enum.proto

#include "google/protobuf/unittest_preserve_unknown_enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace proto3_preserve_unknown_enum_unittest {
class MyMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MyMessage> _instance;
  int oneof_e_1_;
  int oneof_e_2_;
} _MyMessage_default_instance_;
class MyMessagePlusExtraDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MyMessagePlusExtra> _instance;
  int oneof_e_1_;
  int oneof_e_2_;
} _MyMessagePlusExtra_default_instance_;
}  // namespace proto3_preserve_unknown_enum_unittest
static void InitDefaultsscc_info_MyMessage_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto3_preserve_unknown_enum_unittest::_MyMessage_default_instance_;
    new (ptr) ::proto3_preserve_unknown_enum_unittest::MyMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto3_preserve_unknown_enum_unittest::MyMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MyMessage_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MyMessage_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto}, {}};

static void InitDefaultsscc_info_MyMessagePlusExtra_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto3_preserve_unknown_enum_unittest::_MyMessagePlusExtra_default_instance_;
    new (ptr) ::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MyMessagePlusExtra_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MyMessagePlusExtra_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, e_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, repeated_e_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, repeated_packed_e_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, repeated_packed_unexpected_e_),
  offsetof(::proto3_preserve_unknown_enum_unittest::MyMessageDefaultTypeInternal, oneof_e_1_),
  offsetof(::proto3_preserve_unknown_enum_unittest::MyMessageDefaultTypeInternal, oneof_e_2_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessage, o_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, e_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, repeated_e_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, repeated_packed_e_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, repeated_packed_unexpected_e_),
  offsetof(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtraDefaultTypeInternal, oneof_e_1_),
  offsetof(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtraDefaultTypeInternal, oneof_e_2_),
  PROTOBUF_FIELD_OFFSET(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra, o_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::proto3_preserve_unknown_enum_unittest::MyMessage)},
  { 12, -1, sizeof(::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::proto3_preserve_unknown_enum_unittest::_MyMessage_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::proto3_preserve_unknown_enum_unittest::_MyMessagePlusExtra_default_instance_),
};

const char descriptor_table_protodef_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n4google/protobuf/unittest_preserve_unkn"
  "own_enum.proto\022%proto3_preserve_unknown_"
  "enum_unittest\"\301\003\n\tMyMessage\0228\n\001e\030\001 \001(\0162-"
  ".proto3_preserve_unknown_enum_unittest.M"
  "yEnum\022A\n\nrepeated_e\030\002 \003(\0162-.proto3_prese"
  "rve_unknown_enum_unittest.MyEnum\022L\n\021repe"
  "ated_packed_e\030\003 \003(\0162-.proto3_preserve_un"
  "known_enum_unittest.MyEnumB\002\020\001\022\\\n\034repeat"
  "ed_packed_unexpected_e\030\004 \003(\01626.proto3_pr"
  "eserve_unknown_enum_unittest.MyEnumPlusE"
  "xtra\022B\n\toneof_e_1\030\005 \001(\0162-.proto3_preserv"
  "e_unknown_enum_unittest.MyEnumH\000\022B\n\toneo"
  "f_e_2\030\006 \001(\0162-.proto3_preserve_unknown_en"
  "um_unittest.MyEnumH\000B\003\n\001o\"\373\003\n\022MyMessageP"
  "lusExtra\022A\n\001e\030\001 \001(\01626.proto3_preserve_un"
  "known_enum_unittest.MyEnumPlusExtra\022J\n\nr"
  "epeated_e\030\002 \003(\01626.proto3_preserve_unknow"
  "n_enum_unittest.MyEnumPlusExtra\022U\n\021repea"
  "ted_packed_e\030\003 \003(\01626.proto3_preserve_unk"
  "nown_enum_unittest.MyEnumPlusExtraB\002\020\001\022`"
  "\n\034repeated_packed_unexpected_e\030\004 \003(\01626.p"
  "roto3_preserve_unknown_enum_unittest.MyE"
  "numPlusExtraB\002\020\001\022K\n\toneof_e_1\030\005 \001(\01626.pr"
  "oto3_preserve_unknown_enum_unittest.MyEn"
  "umPlusExtraH\000\022K\n\toneof_e_2\030\006 \001(\01626.proto"
  "3_preserve_unknown_enum_unittest.MyEnumP"
  "lusExtraH\000B\003\n\001o*#\n\006MyEnum\022\007\n\003FOO\020\000\022\007\n\003BA"
  "R\020\001\022\007\n\003BAZ\020\002*\?\n\017MyEnumPlusExtra\022\t\n\005E_FOO"
  "\020\000\022\t\n\005E_BAR\020\001\022\t\n\005E_BAZ\020\002\022\013\n\007E_EXTRA\020\003B,\242"
  "\002\014UnknownEnums\252\002\032Google.Protobuf.TestPro"
  "tosb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_sccs[2] = {
  &scc_info_MyMessage_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto.base,
  &scc_info_MyMessagePlusExtra_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto = {
  false, false, descriptor_table_protodef_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto, "google/protobuf/unittest_preserve_unknown_enum.proto", 1211,
  &descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_once, descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_sccs, descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto::offsets,
  file_level_metadata_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto, 2, file_level_enum_descriptors_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto, file_level_service_descriptors_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto)), true);
namespace proto3_preserve_unknown_enum_unittest {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MyEnum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto);
  return file_level_enum_descriptors_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto[0];
}
bool MyEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MyEnumPlusExtra_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto);
  return file_level_enum_descriptors_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto[1];
}
bool MyEnumPlusExtra_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void MyMessage::InitAsDefaultInstance() {
  ::proto3_preserve_unknown_enum_unittest::_MyMessage_default_instance_.oneof_e_1_ = 0;
  ::proto3_preserve_unknown_enum_unittest::_MyMessage_default_instance_.oneof_e_2_ = 0;
}
class MyMessage::_Internal {
 public:
};

MyMessage::MyMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  repeated_e_(arena),
  repeated_packed_e_(arena),
  repeated_packed_unexpected_e_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto3_preserve_unknown_enum_unittest.MyMessage)
}
MyMessage::MyMessage(const MyMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      repeated_e_(from.repeated_e_),
      repeated_packed_e_(from.repeated_packed_e_),
      repeated_packed_unexpected_e_(from.repeated_packed_unexpected_e_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  e_ = from.e_;
  clear_has_o();
  switch (from.o_case()) {
    case kOneofE1: {
      _internal_set_oneof_e_1(from._internal_oneof_e_1());
      break;
    }
    case kOneofE2: {
      _internal_set_oneof_e_2(from._internal_oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:proto3_preserve_unknown_enum_unittest.MyMessage)
}

void MyMessage::SharedCtor() {
  e_ = 0;
  clear_has_o();
}

MyMessage::~MyMessage() {
  // @@protoc_insertion_point(destructor:proto3_preserve_unknown_enum_unittest.MyMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MyMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (has_o()) {
    clear_o();
  }
}

void MyMessage::ArenaDtor(void* object) {
  MyMessage* _this = reinterpret_cast< MyMessage* >(object);
  (void)_this;
}
void MyMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MyMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MyMessage& MyMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MyMessage_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto.base);
  return *internal_default_instance();
}


void MyMessage::clear_o() {
// @@protoc_insertion_point(one_of_clear_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  switch (o_case()) {
    case kOneofE1: {
      // No need to clear
      break;
    }
    case kOneofE2: {
      // No need to clear
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = O_NOT_SET;
}


void MyMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  repeated_e_.Clear();
  repeated_packed_e_.Clear();
  repeated_packed_unexpected_e_.Clear();
  e_ = 0;
  clear_o();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MyMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .proto3_preserve_unknown_enum_unittest.MyEnum e = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      // repeated .proto3_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_repeated_e(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_repeated_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      // repeated .proto3_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_repeated_packed_e(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_repeated_packed_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_unexpected_e = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_repeated_packed_unexpected_e(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_repeated_packed_unexpected_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      // .proto3_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_oneof_e_1(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      // .proto3_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_oneof_e_2(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MyMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto3_preserve_unknown_enum_unittest.MyEnum e = 1;
  if (this->e() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_e(), target);
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
  {
    int byte_size = _repeated_e_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          2, repeated_e_, byte_size, target);
    }
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
  {
    int byte_size = _repeated_packed_e_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          3, repeated_packed_e_, byte_size, target);
    }
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_unexpected_e = 4;
  {
    int byte_size = _repeated_packed_unexpected_e_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          4, repeated_packed_unexpected_e_, byte_size, target);
    }
  }

  // .proto3_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 5;
  if (_internal_has_oneof_e_1()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_oneof_e_1(), target);
  }

  // .proto3_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 6;
  if (_internal_has_oneof_e_2()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      6, this->_internal_oneof_e_2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto3_preserve_unknown_enum_unittest.MyMessage)
  return target;
}

size_t MyMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnum repeated_e = 2;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_repeated_e_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_repeated_e(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _repeated_e_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnum repeated_packed_e = 3 [packed = true];
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_repeated_packed_e_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_repeated_packed_e(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _repeated_packed_e_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_unexpected_e = 4;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_repeated_packed_unexpected_e_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_repeated_packed_unexpected_e(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _repeated_packed_unexpected_e_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .proto3_preserve_unknown_enum_unittest.MyEnum e = 1;
  if (this->e() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_e());
  }

  switch (o_case()) {
    // .proto3_preserve_unknown_enum_unittest.MyEnum oneof_e_1 = 5;
    case kOneofE1: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_oneof_e_1());
      break;
    }
    // .proto3_preserve_unknown_enum_unittest.MyEnum oneof_e_2 = 6;
    case kOneofE2: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MyMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const MyMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MyMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto3_preserve_unknown_enum_unittest.MyMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto3_preserve_unknown_enum_unittest.MyMessage)
    MergeFrom(*source);
  }
}

void MyMessage::MergeFrom(const MyMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  repeated_e_.MergeFrom(from.repeated_e_);
  repeated_packed_e_.MergeFrom(from.repeated_packed_e_);
  repeated_packed_unexpected_e_.MergeFrom(from.repeated_packed_unexpected_e_);
  if (from.e() != 0) {
    _internal_set_e(from._internal_e());
  }
  switch (from.o_case()) {
    case kOneofE1: {
      _internal_set_oneof_e_1(from._internal_oneof_e_1());
      break;
    }
    case kOneofE2: {
      _internal_set_oneof_e_2(from._internal_oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
}

void MyMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessage::CopyFrom(const MyMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto3_preserve_unknown_enum_unittest.MyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessage::IsInitialized() const {
  return true;
}

void MyMessage::InternalSwap(MyMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  repeated_e_.InternalSwap(&other->repeated_e_);
  repeated_packed_e_.InternalSwap(&other->repeated_packed_e_);
  repeated_packed_unexpected_e_.InternalSwap(&other->repeated_packed_unexpected_e_);
  swap(e_, other->e_);
  swap(o_, other->o_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata MyMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MyMessagePlusExtra::InitAsDefaultInstance() {
  ::proto3_preserve_unknown_enum_unittest::_MyMessagePlusExtra_default_instance_.oneof_e_1_ = 0;
  ::proto3_preserve_unknown_enum_unittest::_MyMessagePlusExtra_default_instance_.oneof_e_2_ = 0;
}
class MyMessagePlusExtra::_Internal {
 public:
};

MyMessagePlusExtra::MyMessagePlusExtra(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  repeated_e_(arena),
  repeated_packed_e_(arena),
  repeated_packed_unexpected_e_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
}
MyMessagePlusExtra::MyMessagePlusExtra(const MyMessagePlusExtra& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      repeated_e_(from.repeated_e_),
      repeated_packed_e_(from.repeated_packed_e_),
      repeated_packed_unexpected_e_(from.repeated_packed_unexpected_e_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  e_ = from.e_;
  clear_has_o();
  switch (from.o_case()) {
    case kOneofE1: {
      _internal_set_oneof_e_1(from._internal_oneof_e_1());
      break;
    }
    case kOneofE2: {
      _internal_set_oneof_e_2(from._internal_oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
}

void MyMessagePlusExtra::SharedCtor() {
  e_ = 0;
  clear_has_o();
}

MyMessagePlusExtra::~MyMessagePlusExtra() {
  // @@protoc_insertion_point(destructor:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MyMessagePlusExtra::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (has_o()) {
    clear_o();
  }
}

void MyMessagePlusExtra::ArenaDtor(void* object) {
  MyMessagePlusExtra* _this = reinterpret_cast< MyMessagePlusExtra* >(object);
  (void)_this;
}
void MyMessagePlusExtra::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MyMessagePlusExtra::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MyMessagePlusExtra& MyMessagePlusExtra::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MyMessagePlusExtra_google_2fprotobuf_2funittest_5fpreserve_5funknown_5fenum_2eproto.base);
  return *internal_default_instance();
}


void MyMessagePlusExtra::clear_o() {
// @@protoc_insertion_point(one_of_clear_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  switch (o_case()) {
    case kOneofE1: {
      // No need to clear
      break;
    }
    case kOneofE2: {
      // No need to clear
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = O_NOT_SET;
}


void MyMessagePlusExtra::Clear() {
// @@protoc_insertion_point(message_clear_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  repeated_e_.Clear();
  repeated_packed_e_.Clear();
  repeated_packed_unexpected_e_.Clear();
  e_ = 0;
  clear_o();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MyMessagePlusExtra::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_repeated_e(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_repeated_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_repeated_packed_e(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_repeated_packed_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_unexpected_e = 4 [packed = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_repeated_packed_unexpected_e(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_repeated_packed_unexpected_e(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_oneof_e_1(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_oneof_e_2(static_cast<::proto3_preserve_unknown_enum_unittest::MyEnumPlusExtra>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MyMessagePlusExtra::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
  if (this->e() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_e(), target);
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
  {
    int byte_size = _repeated_e_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          2, repeated_e_, byte_size, target);
    }
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
  {
    int byte_size = _repeated_packed_e_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          3, repeated_packed_e_, byte_size, target);
    }
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_unexpected_e = 4 [packed = true];
  {
    int byte_size = _repeated_packed_unexpected_e_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          4, repeated_packed_unexpected_e_, byte_size, target);
    }
  }

  // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 5;
  if (_internal_has_oneof_e_1()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_oneof_e_1(), target);
  }

  // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 6;
  if (_internal_has_oneof_e_2()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      6, this->_internal_oneof_e_2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  return target;
}

size_t MyMessagePlusExtra::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_e = 2;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_repeated_e_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_repeated_e(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _repeated_e_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_e = 3 [packed = true];
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_repeated_packed_e_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_repeated_packed_e(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _repeated_packed_e_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra repeated_packed_unexpected_e = 4 [packed = true];
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_repeated_packed_unexpected_e_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_repeated_packed_unexpected_e(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _repeated_packed_unexpected_e_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra e = 1;
  if (this->e() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_e());
  }

  switch (o_case()) {
    // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_1 = 5;
    case kOneofE1: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_oneof_e_1());
      break;
    }
    // .proto3_preserve_unknown_enum_unittest.MyEnumPlusExtra oneof_e_2 = 6;
    case kOneofE2: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MyMessagePlusExtra::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  GOOGLE_DCHECK_NE(&from, this);
  const MyMessagePlusExtra* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MyMessagePlusExtra>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
    MergeFrom(*source);
  }
}

void MyMessagePlusExtra::MergeFrom(const MyMessagePlusExtra& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  repeated_e_.MergeFrom(from.repeated_e_);
  repeated_packed_e_.MergeFrom(from.repeated_packed_e_);
  repeated_packed_unexpected_e_.MergeFrom(from.repeated_packed_unexpected_e_);
  if (from.e() != 0) {
    _internal_set_e(from._internal_e());
  }
  switch (from.o_case()) {
    case kOneofE1: {
      _internal_set_oneof_e_1(from._internal_oneof_e_1());
      break;
    }
    case kOneofE2: {
      _internal_set_oneof_e_2(from._internal_oneof_e_2());
      break;
    }
    case O_NOT_SET: {
      break;
    }
  }
}

void MyMessagePlusExtra::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessagePlusExtra::CopyFrom(const MyMessagePlusExtra& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto3_preserve_unknown_enum_unittest.MyMessagePlusExtra)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessagePlusExtra::IsInitialized() const {
  return true;
}

void MyMessagePlusExtra::InternalSwap(MyMessagePlusExtra* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  repeated_e_.InternalSwap(&other->repeated_e_);
  repeated_packed_e_.InternalSwap(&other->repeated_packed_e_);
  repeated_packed_unexpected_e_.InternalSwap(&other->repeated_packed_unexpected_e_);
  swap(e_, other->e_);
  swap(o_, other->o_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata MyMessagePlusExtra::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto3_preserve_unknown_enum_unittest
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::proto3_preserve_unknown_enum_unittest::MyMessage* Arena::CreateMaybeMessage< ::proto3_preserve_unknown_enum_unittest::MyMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto3_preserve_unknown_enum_unittest::MyMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra* Arena::CreateMaybeMessage< ::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto3_preserve_unknown_enum_unittest::MyMessagePlusExtra >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
